sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "4.0.0"
  - "4"
  - "6"
  - "8"
  - "10"
  - "node"
before_script:
  - npm prune
script:
  - npm test
  - npm run cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
