sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "node"
before_install:
  - npm install -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
